services: 
  postgres:
    image: postgres:17.5-alpine3.21
    restart: unless-stopped
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data


